default:
    site:
        review_period: '13 months'
        spaces:
            -
                space_path: nxdoc
                space_name: Developer Documentation Center
            -
                space_path: userdoc
                space_name: Nuxeo Platform User Documentation

        versions:
            -
                label: FT
                is_current_version: true
            -
                label: LTS 2016
                url_path: '810'
            -
                label: LTS 2015
                url_path: '710'
            -
                label: '6.0'
                url_path: '60'
            -
                label: '5.8'
                url_path: '58'

development:
    isDev: true
